steps:
  # Build the frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend']
    id: BuildFrontend

  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', './backend']
    id: BuildBackend

  # Push the frontend Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend']
    id: PushFrontend

  # Push the backend Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend']
    id: PushBackend

images:
  - 'gcr.io/$PROJECT_ID/frontend'
  - 'gcr.io/$PROJECT_ID/backend'